### ISSUE TITLE
My guests or rescued people leave immediately when colonists put them inside

### ISSUE THREAD

**Issue by Leonixar** [sumghai/MedPod#78] opened 2023-08-08 01:32 UTC
**Describe the bug:**  
My guests or rescued pawns leave immediately when colonists put them inside...

**Expected behavior:**  
Stay there, so the MedPod can heal them... :D

**Steps to reproduce:**  

1. DUNNO, SORRY :(
2. DUNNO, SORRY :(
3. DUNNO, SORRY :(

**Additional information:**

## System and Game Configuration
**Operating System:** Microsoft Windows 10 (64-bit)
**Physical RAM:** 32.0 GB
**RimWorld base game version:** 1.4.3704
**RimWorld DLCs loaded:** ALL
**MedPod mod version:** 1.5.12
**MedPod mod downloaded from:** Steam
**Your mod list:** 

I'm sorry, but I will not search for version numbers of all my mods...
Also the list bellow is in load order.

Harmony
No Version Warning
Mod Manager
Core
Royalty
Ideology
Biotech
HugsLib
TDS Bug Fixes
TD Find Lib
JecsTools
Vanilla Expanded Framework
Miscellaneous 'CORE'
Vehicle Framework
Ability to Read
RimPy Mod Manager Database
Humanoid Alien Races
Tabula Rasa
XML Extensions
Lizard's Patches
Enable Oversized Weapons
Glitter Tech
[SYR] Processor Framework
Stuffed Floors
RIMkea
Vanilla Fishing Expanded
ReGrowth: Core
Infinite Turrets
A Dog Said... Animal Prosthetics
Advanced Bridges
Advanced Power Plus
Alpha Animals
Clean Textures
Vanilla Textures Expanded
Graphics Settings+
Androids for RW 1.4
Dubs Bad Hygiene
Hospital
Hospitality
Android Tiers Reforged
Androids Expanded for RW 1.4
Birds Beyond: Temperate Forest
Research Reinvented
Replace Stuff
PowerSwitch
Door Mat
Doors Expanded
ED-Laser-Drill (Continued)
Halo UNSC Weapon Pack
Vanilla Weapons Expanded - Non-Lethal
Shield Generators
Egg Incubator
Electric Stonecutting Table
Stonecutting Extended
EPOE 1.4 (Expanded Prosthetics and Organ Engineering)
Expanded Roofing 1.4
Fences And Floors (Continued)
Glass+Lights
Windows
Megafauna
Mines
Misc. Robots
Misc. Robots++
Misc. Training
[T] MoreFloors 1.4
Quarry
Rah's Bionics and Surgery Expansion
Repair Workbench
Replimat
Alpha Bees
Rimefeller
RimFridge Updated
Rimworld: Spartan Foundry (Continued)
Raise The Roof 1.4
Roof Support 1.4
RT Solar Flare Shield
RT Fuse
Signs and Comments
Tables+
Vanilla Apparel Expanded
Vanilla Armour Expanded
Vanilla Furniture Expanded
Vanilla Furniture Expanded - Farming
Vanilla Furniture Expanded - Medical Module
Vanilla Furniture Expanded - Production
Vanilla Furniture Expanded - Security
Vanilla Furniture Expanded - Architect
Simple Utilities: Wall
Vanilla Furniture Expanded - Power
Vanilla Furniture Expanded - Art
Vanilla Furniture Expanded - Spacer Module
Vanilla Outposts Expanded
Vanilla Weapons Expanded
Various Space Ship Chunk (Continued)
VGP Vegetable Garden
VGP Garden Canning
VGP Garden Drinks
VGP Garden Dyes
VGP Garden Fabrics
VGP Garden Gourmet
VGP Garden Medicine
VGP Garden Resources
VGP Garden Tools
VGP Soylent Production
Vanilla Vehicles Expanded
[Vehicle Framework] Aircrafts and Bombs
Snow Crawler
InfestationBait
Defensive Machine Gun Turret Pack
More Furniture (Continued)
Outdoor Lighting (continued)
Wall Light
Wheelchairs
Furnace
[RH2] Chicken Mitchell² - Hairstyles
Vanilla Hair Expanded
Better Vanilla Masking
[SYR] Bullet Casings
Medical IVs
MedPod
ED-CheatReactor
Project RimFactory Revived
Satellite
MiningCo. Spaceship
Terraform Rimworld
Dub's Paint Shop
Dubs Rimatomics
Dubs Rimkit
Dubs Skylights
What the hack?!
Rim-Effect: Core
Rim-Effect: Asari and Reapers
Style Revised - Animalist
Embrasures
Power++
Underground Power Conduits
Mercer's Backpacks (Continued)
CleaningStation
Animal Tab
Animal Variety Coats
Animals Logic
Area Unlocker
Backup Power
Ben Lubar's Vanilla Expanded Patches
Better Pawn Control
All Memories Fade
Survival Tools
Allow Tool
Auto links
Better Workbench Management
Bionic icons
Blueprints
Camera+
Categorized Bill Dropdown
Chickens Efficient Light
Choose Your Recipe
Clean Pathfinding 2
RPG Style Inventory
Cleaning Priority (Continued)
Cleaning Speed
Collapser
Colony Manager
CM Color Coded Mood Bar [1.1+]
Command Palette
Conduit Deconstruct
Death Rattle Continued [1.2+]
Desire Paths
DontBlockDoor
DragSelect
Dress Patients (1.4)
Dubs Apparel Tweaks
Dubs Break Mod
Dubs Mint Menus
Dubs Mint Minimap
Dubs Performance Analyzer
Pharmacist (Forked with blood rot fix)
Everybody Gets One
[NL] Facial Animation - WIP
[FSF] Filth Vanishes With Rain And Time
Follow Me
Foxes Aren't Suicidal(continued)
Geological Landforms
Biome Transitions
Harvest Organs Post Mortem
Haul to Stack
Interaction Bubbles
Kill For Me
Level Up!
Life Support Continued [1.1+]
LightsOut
Locks
Medical Tab
MinifyEverything
Moody
More Faction Interaction (Continued)
More Harvest Designators!
More Planning [1.4]
More Than Capable
More Trade Ships (Continued)
[KV] More Trait Slots [1.4]
Mortar Accuracy
Music Manager
Beautiful Outdoors
Need Bar Overflow
Not My Fault
Numbers
Optimization: Meats - C# Edition
[KV] Path Avoid
Perspective: Buildings
Perspective: Doors
Perspective: Trees
Pharmacist Temporary 1.4 Update
Predator Hunt Alert
Prisoners Dont Have Keys
Prisoners Should Fear Turrets
Quick Stockpile Creation
RaiderInfo
Realistic Rooms Rewritten
Reasonable Components
Recipe icons (Continued)
[KV] ReColor Stockpile &amp; Growing Zones
Relations Tab
Replace Stuff Mod Compatibility
RimHUD
Run and Hide (Continued)
[KV] Save Storage, Outfit, Crafting, Drug, &amp; Operation Settings [1.4]
Simple FX: Smoke
Scattered Flames
Scattered Stones
[SYR] Set Up Camp
Share The Load
Shit Rimworld Says
Simple sidearms
Simple Sidearms - Switch Weapon
[CAT] Show Hair With Hats or Hide All Hats
Simple Utilities: Ceiling
Skilled Stonecutting [1.4]
Smart Farming
Smart Turret Covering
Snap Out!
Sometimes Raids Go Wrong
Stabilize
Stop, Drop, And Roll! [BAL]
Stackable Chunks [1.4+]
OgreStack
Stockpile Ranking
Tilled Soil
Toggle Harvest
Toggleable Overlays
[GMT] Trading Spot
Turn It On and Off - RePowered
Ugh You Got Me
Veinminer R1.1
Where is my weapon?
Work Tab
Yayo's Animation (Continued)
ZiTools objects seeker
Cheaper Components
Fluffy Breakdowns
Smarter Construction
Smarter Deconstruction and Mining
4M Mehni's Misc Modifications [1.2+]
ED-EnhancedOptions [1.4]
RIMMSqol
ResearchPal - 1.4 Repackage
Reverse Commands
Terrain Zone Selections
Material Filter
Filter Manager
QualityBuilder
Work Manager
Sowing Manager
Common Sense
Faction Control 1.4
[LC] Consolidated Traits
[KV] Configurable Maps (Continued)
Character Editor
Pick Up And Haul
[KV] Change Skill Levels &amp; Don't Lose Levels
10x Carrying Capacity (Continued)

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, MedPod and its dependencies
- [x] I am NOT running any mods with known incompatibilities with MedPod
- [ ] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [ ] I have confirmed that the issue does not happen if MedPod is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [ ] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment] 2023-08-18 07:32
Closing due to insufficient reproduction steps and no follow-up.

**Closed by sumghai** 2023-08-18 07:32 UTC
Labels: Bug, Invalid / Won't Fix / No Follow-Up
