### ISSUE TITLE
Animals not using VetPod

### ISSUE THREAD

**Issue by aarmicsta** [sumghai/MedPod#94] opened 2024-07-02 15:54 UTC
**Describe the bug:**  

Animals are not using VetPods

**Expected behavior:**  

Animals heal using VetPods

**Steps to reproduce:**  

1. Place VetPod
2. Have injured animal
3.

**Additional information:**

I disabled all mods (except Harmony and MedPod). No error messages.

## System and Game Configuration
**Operating System:** 
Microsoft Windows 11 (64-bit)
**Physical RAM:** 
128GB
**RimWorld base game version:** 
1.5.4104
**RimWorld DLCs loaded:** 
Royalty, Ideology, Biotech, Anamoly
**MedPod mod version:** 
1.5.29
**MedPod mod downloaded from:** 
Steam
**Your mod list:** 
Harmony 2.3.1.0
MedPod 1.5.29

## Declaration

I hereby verify that:
- [X] I am running the latest version of the game, MedPod and its dependencies
- [X] I am NOT running any mods with known incompatibilities with MedPod
- [X] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [X] I have confirmed that the issue does not happen if MedPod is disabled
- [X] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [X] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment] 2024-07-03 05:45
Thank you for your bug report, @aarmicsta - did you check that the animal(s) have their required medical treatment level set to Industrial medicine or above?

**Comment by aarmicsta** [comment] 2024-07-03 11:19
> Thank you for your bug report, @aarmicsta - did you check that the animal(s) have their required medical treatment level set to Industrial medicine or above?

Thanks for the response! I did double check, the animals have their med treatement level set to the highest possible.

**Comment by sumghai** [comment] 2024-07-03 20:14
@aarmicsta - Could you send me your savefile with just the bare minimum number of mods required to reproduce this issue? You should be able to just drag 'n drop your savefile here on GitHub.

**Comment by aarmicsta** [comment] 2024-07-03 20:59
Here's a save file, only Core and DLCs installed, along with Harmony and MedPod.  Can't attach the file directly to this thread, so here's the link to the file in a temporary private repository I set up here on Github.

https://github.com/aarmicsta/TempStuff/blob/84af0bb05e8efb93fb52e3f80b72abf0205846a3/VetPod%20Test%20Game.rws

**Comment by sumghai** [comment] 2024-07-04 05:47
@aarmicsta - Unfortunately, I cannot access the savegame you uploaded to your private repository, as I get a "404 not found" error message.

Try compressing your savegame inside a ZIP archive first, and then drag 'n drop to upload (GitHub supports ZIP files).

**Comment by aarmicsta** [comment] 2024-07-04 09:07
Good idea! Here is the ZIP archive. I appreciate all of your effort.

[VetPod.zip](https://github.com/user-attachments/files/16096184/VetPod.zip)

**Comment by sumghai** [comment] 2024-07-04 10:06
Thanks for the savefile! Yeah, looks like something fishy is going on with the animal thinktree. I'll take a closer look this weekend.

**Comment by aarmicsta** [comment] 2024-07-04 22:56
Great! Thanks, I really appreciate it!

**Comment by nekkidtruth** [comment] 2024-07-06 16:37
Oh thank god, I thought I was going crazy!

**Comment by sumghai** [comment] 2024-07-08 06:11
Should be fixed now.

**Closed by sumghai** 2024-07-08 06:12 UTC
Labels: Bug
