### ISSUE TITLE
Add a check to operations queue to stop any attempt to remove sedated hediff

### ISSUE THREAD

**Issue by CMaia1** [sumghai/MedPod#60] opened 2021-11-25 16:12 UTC
**Describe your idea:**

Add a check to any operations still in queue to pawns to not try to remove sedated hediff via medpod until all of them is done

**Why do you think your idea would be a good fit for MedPod?:**
My pawns always try to remove sedated hediff between surgeries and this is work going to waste

**What alternatives/workarounds have you tried?**
Watch carefully and cancels any attempt to move the patient to medpod between surgeries

## Declaration

I hereby verify that:
- [x] I have searched the issue tracker and confirmed no-one else has already suggested my idea before
- [x] I understand that my idea will be closed and ignored if I do not fill this form properly, or if the mod author decides that my idea doesn't fit the scope of the mod

**Comment by sumghai** [comment] 2021-11-26 04:34
AFAIK, there is no hediff explicitly named "sedated" - there is a `Anesthetic` hediff that happens to have a "sedated" stage.

MedPods by design always clears anesthesia in pawns, so that pawns who have completed treatment will get off as soon as possible to let any other patients use it.

But more importantly, I'm struggling to understand the context behind this issue.

* Pawns who have been anesthetized for a medical operation can't get up from medical beds at all to use MedPods, or carried by other pawns to MedPods.

* Pawns shouldn't even be having surgery conducted on MedPods; this mod specifically tells surgeons not to operate or feed MedPod patients.

**Comment by CMaia1** [comment] 2021-11-26 20:04
My pawns are carring others with sedated stage (1% consciousness max) with multiple surgeries (e.g add prostetics and remove limbs) still in queue to medpods between operations and the medpod is removing it to after that continue to the next one in queue and getting anesthetized again and so on. They are being operated in normal hospital beds like in vanilla, not in medpods hence why it's being transported to one medpod.

I hope it's clear now

**Comment by sumghai** [comment] 2021-11-26 23:52
Which third-party mod is allowing doctors to carry pawns between beds? Because AFAIK, doctors can only rescue unconscious pawns lying on the ground, and once a patient is assigned to a medical bed (MedPod or non-MedPod), they stay there.

**Comment by CMaia1** [comment] 2021-11-28 13:18
This is happening:
-The patient is going to rest in hospital bed to be operated;
-Some doctor operate the patient using the operations order;
-the doctor sometimes do something else instead of just do the next one (usually this happens when some pawn is carring the body part that will be using in surgery to storage or they need to eat/sleep asap);
-some pawn carry the patient to medbay to remove the anesthetic headiff;
-the patient goes to bed again and the cycle continues.

**Comment by sumghai** [comment] 2021-11-29 01:47
> -some pawn carry the patient to medbay to remove the anesthetic headiff;

Does this happen if you have a savegame with *only* Harmony, Core and MedPod?

As I mentioned previously, carrying pawns between medical beds does not sound like normal vanilla RimWorld behaviour.

**Comment by sumghai** [comment] 2021-12-14 05:31
Closing this "feature request" (really, a bug report) due to lack of follow up.

@CMaia1, feel free to reopen this issue once you have identified the conflicting third-party mod(s) (other than MedPod) causing this behaviour.

**Closed by sumghai** 2021-12-14 05:31 UTC
Labels: New Feature, Needs More Info
