### ISSUE TITLE
Deadlock to the diagnostic state

### ISSUE THREAD

**Issue by gogochlwns** [sumghai/MedPod#14] opened 2020-07-10 16:18 UTC
When you enter the Medpod, there is a symptom that only the diagnosis is repeated and no treatment is given.

**Comment by sumghai** [comment] 2020-07-10 22:57
This isn't much information to go on.

What hediff(s) does the patient pawn have that causing the MedPod to be stuck in diagnostic mode?

Are you running any other mods that may affect pawn behaviour on medical beds? (Please **do not** give me your full modlist - instead, try to reproduce the problem on a new savegame with the minimum number of third-party mods)

**Comment by DJNokem** [comment] 2020-07-13 18:18
I've come across this issue.  It seems to be linked to my pawns having any of the skin glands (armor/tough/stone)  I've tried both the normal Medpod and the Lux versions.  Removing the glands, even if the pawn in on the Medpod at the time seems to fix the issue.

**Comment by sumghai** [comment] 2020-07-14 12:22
Seems to be related to #17, then.

**Comment by sumghai** [comment] 2020-07-22 12:27
Closing this issue, as the root cause is described in #17.

**Closed by sumghai** 2020-07-22 12:27 UTC
Labels: Bug
