### ISSUE TITLE
Pawns with prosthetic arms / legs stuck in treatment loop

### ISSUE THREAD

**Issue by bauch1234** [sumghai/MedPod#73] opened 2022-11-19 04:50 UTC
**Describe the bug:**  
after update colonist flock to the med pods and stay there it in a loop

**Expected behavior:**  
them not to go to the pod no hediffs are negitive  

**Steps to reproduce:**  

1.sorry im about to go to bed but i can give the list of hediffs on my pawns in a screenshot 
2.i have iud/ vasectomy on all my pawns and both males and females are affected so i know its not that 
3.

**Additional information:**

![bug for med pod](https://user-images.githubusercontent.com/5841064/202834550-064e11aa-2688-413f-946c-63a2bc8aadfe.PNG)

## System and Game Configuration
**Operating System:** Microsoft Windows 10 (64-bit)
**Physical RAM:** 16.0 GB
**RimWorld base game version:** 1.4.3542
**RimWorld DLCs loaded:** all
**MedPod mod version:** 1.5.5
**MedPod mod downloaded from:** steam
**Your mod list:** harmony 2.2.2, hugslib10.0.1,medpod 1.5.5,rimatomics 1.7.25

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, MedPod and its dependencies
- [x] I am NOT running any mods with known incompatibilities with MedPod
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if MedPod is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment] 2022-11-19 05:27
Alright, I've confirmed the bug.

It looks like the latest update that flags all "bad" hediffs needing treatment specifically conflicts with prosthetic arms and legs, because the child body parts are regarded as missing (and also "bad").

**Comment by sumghai** [comment] 2022-11-19 06:56
Fixed via 71787089af42ad444eb694646c4d5333ca613add and 3b4ad8c5040c3273b0dea6f16912ddd4c407b1c8

**Closed by sumghai** 2022-11-19 06:56 UTC
Labels: Bug

**Comment by bauch1234** [comment] 2022-11-19 15:02
i would like to thank you for your quick response and patch work
