### ISSUE TITLE
Conflict with Reconditioning Pod 

### ISSUE THREAD

**Issue by blkarcher77** [sumghai/MedPod#24] opened 2020-07-24 21:25 UTC
Hey, Im not sure if this is where I should mention this, or if I should mention this at all, but I have found a bug when it comes to another mod. If this isn't the place, let me know.

So this mod, [Reconditioning Pod](https://steamcommunity.com/sharedfiles/filedetails/?id=2044003955), basically allows you to recondition pawn traits. I reconditioned two of my pawns, and then it shows up on their health tab. It tells you how strong the reconditioning is, and when you should send them back to the pod.

So one of the pawns I reconditioned got hurt, and I sent them to the Medpod, and their "Reconditioning" slot disappeared, or got healed. I checked my other pawn, and their reconditioning hasn't disappeared, so it was the Medpod that got rid of it. However, the reconditioning is still working, as the pawn is still industrious over slothful. Additionally, each conditioning pod gets biocoded, meaning only one person can use it, but the pod that the pawn that got healed now says unowned. So it leads me to believe that the medpod basically makes the conditioning permanent. 

Ill be putting this as a bug on the Reconditioning Pod page as well, so delete this if this doesn't belong, but just thought you should know.

**Comment by sumghai** [comment] 2020-07-24 22:42
I took a look at the XML def for the `reconditioned` hediff from the Reconditioning Pod mod:

https://github.com/emipa606/PSReconditioningPod/blob/master/Defs/HediffsDefs/PS_Hediffs_Reconditioned.xml

```
<HediffDef ParentName="DiseaseBase">
	<defName>PS_Hediff_Reconditioned</defName>
	<hediffClass>PS_ReconPod.PS_Hediff_Reconditioned</hediffClass>
	<defaultLabelColor>(0.42,0.63,0.62)</defaultLabelColor>
	<label>reconditioned</label>
	<labelNoun>reconditioned</labelNoun>
	<minSeverity>0.0</minSeverity>
	<maxSeverity>1.0</maxSeverity>
	<scenarioCanAdd>false</scenarioCanAdd>
	<stages>
		<li>
			<label>slipping</label>
			<minSeverity>0</minSeverity>
			<statOffsets>
				<MentalBreakThreshold>0.2</MentalBreakThreshold>
			</statOffsets>
		</li>
		<li>
			<label>weak</label>
			<minSeverity>0.25</minSeverity>
			<statOffsets>
				<MentalBreakThreshold>0.1</MentalBreakThreshold>
			</statOffsets>
		</li>
		<li>
			<label>strong</label>
			<minSeverity>0.5</minSeverity>
			<statOffsets>
				<MentalBreakThreshold>0.03</MentalBreakThreshold>
			</statOffsets>
		</li>
		<li>
			<label>fresh</label>
			<minSeverity>0.75</minSeverity>
		</li>
	</stages>
	<causesNeed>PS_Needs_Reconditioning</causesNeed>
</HediffDef>
```

Basically, the problem is that the author defined the reconditioning as a _disease_, which by default will have the `<isBad>` parameter set to false. The MedPod is designed to treat "bad" hediffs, so that's why your pawn's `reconditioned` hediffs are being removed. 

To fix this, the author/maintainer of the Reconditioning Pod mod should at the very least set `<isBad>false</isBad>` for `PS_Hediff_Reconditioned`. Please contact them to do so.

By the way, please don't delete/censor/blank out this issue. Even though the problem isn't with the MedPod mod, it's still important to have a full record of how the problem was diagnosed, for future reference.

Please let me know once the issue has been fixed on the Reconditioning Pod mod's end, and I'll close this issue.

**Comment by blkarcher77** [comment] 2020-07-24 23:01
Alright, i'll copy this to the other author, because I have no idea what any of that code means. Thanks for the quick response

**Comment by emipa606** [comment] 2020-07-28 17:49
PS_Hediff_Reconditioned should no longer be counted as bad. Thanks for reporting!

**Comment by sumghai** [comment] 2020-07-28 22:20
Much appreciated, @emipa606 :)

@blkarcher77, could you please verify that the latest update to the Recondition Pod mod is now compatible with MedPod?

**Comment by blkarcher77** [comment] 2020-07-28 22:23
Im gonna be completely honest with you, I have no idea how to download from github. Can i download it from the steam version? Because I was using the FPS boosted version of the medpod

**Comment by sumghai** [comment] 2020-07-29 11:45
@blkarcher77 - In this particular instance, there have been no changes to the Steam or GitHub version of MedPod, so you can just test your current Steam version of MedPod with the latest update to the Reconditioning Pod mod from Steam.

**Comment by blkarcher77** [comment] 2020-07-29 22:36
Alright, I downloaded both mods again, and now, my pawn that was reconditioned kept his reconditioned health status. This has been a complete success everybody

@sumghai @emipa606 Round of applause for everyone

**Comment by sumghai** [comment] 2020-07-30 11:50
Good work, team!

**Closed by sumghai** 2020-07-30 11:51 UTC
Labels: Third-Party Mod Issue
